# Generated by Django 5.1.4 on 2026-08-01 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('committed', 'committed'), ('released', 'released'), ('expired', 'expired')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.cart')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.variant')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='inventory_r_status_8d1db9_idx'), models.Index(fields=['variant', 'status'], name='inventory_r_variant_27be36_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='reservation_quantity_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.IntegerField()),
                ('counted', models.IntegerField(blank=True, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.variant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('count', 'variant'), name='uniq_count_variant')],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.variant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('variant', 'location'), name='uniq_stock_level_variant_location'), models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='stock_level_on_hand_gte_0'), models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='stock_level_reserved_gte_0'), models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='stock_level_reserved_lte_on_hand')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('receipt', 'receipt'), ('sale_online', 'sale_online'), ('sale_pos', 'sale_pos'), ('return', 'return'), ('damage', 'damage'), ('loss', 'loss'), ('count_adjustment', 'count_adjustment'), ('correction', 'correction'), ('initial_load', 'initial_load')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=64, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_movements', to='catalog.variant')),
            ],
            options={
                'permissions': [('adjust_stock', 'Can record stock movements'), ('run_count', 'Can open/close stocktakes')],
                'constraints': [models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='stock_movement_delta_nonzero')],
            },
        ),
    ]
