# Generated by Django 5.1.4 on 2026-08-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('create_pos_order', 'Can ring up an in-store sale'), ('fulfil_order', 'Can fulfil order'), ('view_any_order', "Can view any user's order"), ('refund_order', 'Can issue refunds'), ('view_reports', 'Can view sales/stock reports')]},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('card', 'card')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
