# Generated by Django 5.1.4 on 2026-08-01 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('action', models.CharField(max_length=60)),
                ('object_type', models.CharField(max_length=60)),
                ('object_id', models.CharField(max_length=64)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['object_type', 'object_id', '-created_at'], name='audit_audit_object__c70e22_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx')],
            },
        ),
    ]
