# Generated by Django 5.1.4 on 2026-08-01 10:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Trigram fallback for typo-tolerant search (see architecture-spec.md §8.1).
        TrigramExtension(),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('unisex', 'unisex'), ('kids', 'kids')], max_length=20)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('archived', 'archived')], default='draft', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=40)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('price_amount', models.BigIntegerField()),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('compare_at_amount', models.BigIntegerField(blank=True, null=True)),
                ('weight_grams', models.IntegerField(blank=True, null=True)),
                ('online_buffer', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.variant')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'category'], name='catalog_pro_status_9b3667_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalog_pro_search__6e8905_gin'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['sku'], name='catalog_var_sku_93f218_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['barcode'], name='catalog_var_barcode_ef6240_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product'], name='catalog_var_product_5106de_idx'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='uniq_variant_product_size_color'),
        ),
    ]
